### PR TITLE
brought over latest updates from terraform-module-template

### PR DESCRIPTION
**Pull request by alasseter-dds**
@chrisgilmerproj @pjdufour-dds 
this PR fulfills issue #10

### CODE REVIEW

**Comment by alasseter-dds** [comment]
Okay my `circleci` tests are failling so I'm currently troubleshooting the following error message. I'll ping you after I resolve it. 
```
#!/bin/bash -eo pipefail
git diff --exit-code
diff --git a/test/terraform_aws_simple_test.go b/test/terraform_aws_simple_test.go
index 715c568..7e10606 100644
--- a/test/terraform_aws_simple_test.go
+++ b/test/terraform_aws_simple_test.go
@@ -13,12 +13,12 @@ import (
 	"strings"
 	"testing"
 
+	"github.com/aws/aws-sdk-go/aws"
+	"github.com/aws/aws-sdk-go/aws/session"
 	"github.com/aws/aws-sdk-go/service/lambda"
-	"github.com/stretchr/testify/require"
 	"github.com/gruntwork-io/terratest/modules/random"
 	"github.com/gruntwork-io/terratest/modules/terraform"
-	"github.com/aws/aws-sdk-go/aws"
-	"github.com/aws/aws-sdk-go/aws/session"
+	"github.com/stretchr/testify/require"
 )
 
 func TestTerraformSimpleExample(t *testing.T) {

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by alasseter-dds** [comment]
@pjdufour-dds @chrisgilmerproj  Ready for your review whenever you get the chance

**Review by chrisgilmerproj — APPROVED** [review]
🚀

**Comment by alasseter-dds** [comment]
Thank you @chrisgilmerproj . I will merge once @pjdufour-dds has had a chance to take a look & review. No hurry. Thanks!

**Comment by chrisgilmerproj** [comment]
In this case I think it's fine to merge. You typically only need one reviewer for a PR. The last PR I wanted two reviewers to sign off because I'm not the terratest expert. But you're just copying changes I made to the template repo here. So go ahead and merge.

**Pull request merged**
